new post page
uoftblueprint/centre-for-dreams pull request #151
Opened 2023-11-11 22:44 UTC by nm-le

### Description

Create createpost.tsx inside apps/nextjs/src/pages to handle creating new pages. New posts are default to type 'announcement' for now, but will add option for user to select type of post (either announcement or discussion). 

Also during testing I can only create new post by changing createPost to use publicProcedure. This is reflected in the PR but will need to change this back to adminProcedure. Also added /createpost to publicRoutes in middleware.ts to bypass Clerk.

<img width="508" alt="image" src="https://github.com/uoftblueprint/centre-for-dreams/assets/85861290/5da16faa-5f76-4542-8ac7-2ab480dc04c3">
 

<img width="1281" alt="image" src="https://github.com/uoftblueprint/centre-for-dreams/assets/85861290/2743e856-d843-41d9-9a59-6789a37667ca">

### Reason for Change

Fixes CFD-

Completes CFD-34

Contributes to CFD-

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other

### Testing

- [ ] Test A
- [ ] Test B

2023-11-11 23:44 UTC, BakerWJ requested changes
can you try logging into the website and then trying to access the form and submit?

2023-11-11 23:44 UTC, BakerWJ commented on apps/nextjs/src/middleware.ts
> -  publicRoutes: ["/", "/(api|trpc)(.*)"],
this page should not be public

2023-11-11 23:44 UTC, BakerWJ commented on package.json
> +    "react-hook-form": "^7.48.2",
this should be added to the package.json in the nextjs folder

2023-11-11 23:44 UTC, BakerWJ commented on package.json
> +    "react-query": "^3.39.3",
delete

2023-11-11 23:44 UTC, BakerWJ commented on packages/api/src/router/announcement.ts
> +  createAnnouncement: publicProcedure
revert

2023-11-11 23:44 UTC, BakerWJ commented on apps/nextjs/src/pages/createpost.tsx
> +  };
for now can just leave form unstyled

2023-11-12 01:24 UTC, nm-le commented
Hi, not sure how to fix failed checks after I made the changes to the package.json files. Submitting form works after logging in the website.

2023-11-12 01:33 UTC, BakerWJ commented
Run pnpm i to fix the lockfile

2023-11-12 04:00 UTC, BakerWJ reviewed
looks good -- can you update the image in the PR description? will approve after addressing the one comment

2023-11-12 04:09 UTC, nm-le commented on apps/nextjs/package.json
> +    "react-query": "^3.39.3",
I thought you wanted that :?

![image](https://github.com/uoftblueprint/centre-for-dreams/assets/85861290/80c7f621-b00c-4a71-8c75-2efa4e27891f)

2023-11-12 04:17 UTC, BakerWJ commented on apps/nextjs/package.json
> +    "react-query": "^3.39.3",
not sure why its highlighting both lines for this comment 🥲 -- comment is only about react-query

2023-11-12 04:18 UTC, nm-le commented on apps/nextjs/package.json
> +    "react-query": "^3.39.3",
oh ok makes sense

2023-11-12 04:39 UTC, BakerWJ approved these changes

2023-11-12 05:02 UTC, merged