[CFD-78] Filled Button Components
uoftblueprint/centre-for-dreams pull request #306
Opened 2024-01-10 03:17 UTC by 1zhaohel

### Description

Created Button/Filled and Button/Disabled based on the Figma design which also accepts an `onClick` prop that passes a function to the underlying Button.

### Reason for Change

Completes CFD-78

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Testing

- Tested the button in `index.tsx`
![image](https://github.com/uoftblueprint/centre-for-dreams/assets/129004013/763cae09-6f73-4270-adb3-ed4fdeba01f8)

- Passed a function to the underlying button to see if it would work for filled button

https://github.com/uoftblueprint/centre-for-dreams/assets/129004013/815bb009-f180-4d29-98ba-d4da17f7498f

Recreate:
```
import FilledButton from "~/components/filledbutton";
function sayHello() {
  alert("You clicked me!");
}
<FilledButton
  label="Label"
  onClick={sayHello}
  disabled={true}
></FilledButton>
<br></br>
<br></br>
<FilledButton label="Label" onClick={sayHello}></FilledButton>
```

2024-01-10 03:26 UTC, 1zhaohel commented
not sure if the styling is correct...

2024-01-14 16:29 UTC, BakerWJ requested changes

2024-01-14 16:29 UTC, BakerWJ commented on apps/nextjs/src/components/filledbutton.tsx
> +              {label}
instead of using a label, it might be better to use the children props so it would be like `<Button>Click</Button>`

2024-01-14 16:29 UTC, BakerWJ commented on apps/nextjs/src/components/filledbutton.tsx
This button should be built for the React Native app, not the Nextjs app. You should be able to reuse a lot of the css when making it for RN

2024-01-21 15:10 UTC, BakerWJ reviewed
the PR itself looks good, but it looks like you messed up your git which is why a bunch of files are being changed. I will approve after this is fixed

2024-01-21 15:54 UTC, 1zhaohel commented
> the PR itself looks good, but it looks like you messed up your git which is why a bunch of files are being changed. I will approve after this is fixed

ok 👍

2024-01-21 17:16 UTC, closed without merging