Solarescarlos101/cfd 153 create api endpoint to fetch subactivities for events
uoftblueprint/centre-for-dreams pull request #493
Opened 2024-11-10 21:27 UTC by solarescarlos

### Description

Created the getSubactivities endpoint in packages/api/src/router/activity.ts as described in https://linear.app/uoftblueprint/issue/CFD-153/create-api-endpoint-to-fetch-subactivities-for-events.
When given an activity id, it returns all subactivities in that activity. Included some console logs.

### Reason for Change

https://linear.app/uoftblueprint/issue/CFD-153/create-api-endpoint-to-fetch-subactivities-for-events

Completes CFD ticket https://linear.app/uoftblueprint/issue/CFD-153/create-api-endpoint-to-fetch-subactivities-for-events

### Type of change

- [X] New feature (non-breaking change which adds functionality)

### Testing

- First I added some console log statements within the endpoint. Then, I ran pnpm dev and created a new activity with its own subactivity. I then navigated to the tRPC panel (http://localhost:3000/api/panel) and called getSubactivities under the activity router. I used id 100 (use the id of the activity you created).
![Screenshot (115)](https://github.com/user-attachments/assets/d0b0bd27-dcbc-4225-b804-c2f1559ec459)

2024-11-10 21:31 UTC, solarescarlos commented
Currently fixing format

2024-11-11 21:49 UTC, sarinali requested changes

2024-11-11 21:49 UTC, sarinali commented on packages/api/src/router/activity.ts
> +      console.log("Received input:", input);
No need for this logging statement can you delete this?

2024-11-11 22:00 UTC, sarinali requested changes

2024-11-11 22:00 UTC, sarinali commented on packages/api/src/router/activity.ts
> +      console.log("Query result:", result);
remove this one as well

2024-11-11 22:56 UTC, sarinali approved these changes
LGTM

2024-11-11 22:57 UTC, sarinali requested changes

2024-11-11 22:57 UTC, sarinali commented on packages/api/src/router/activity.ts
> +  getSubactivities: publicProcedure
should be protectedprocedure actually

2024-11-12 00:06 UTC, sarinali approved these changes
LGTM

2024-11-12 01:07 UTC, merged