Adventurer e/cfd 182 create post page
uoftblueprint/centre-for-dreams pull request #510
Opened 2024-12-04 21:10 UTC by Adventurer-E

### Description

### Reason for Change

Fixes CFD-

Completes CFD-182

Contributes to CFD-

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other

### Testing

Tested to create posts on app and succeeded. Posts also show up on Prisma.
<img width="517" alt="Screenshot 2024-12-04 at 4 09 41 PM" src="https://github.com/user-attachments/assets/2ecf2d55-732b-458f-9e63-7d6543851b60">
<img width="517" alt="Screenshot 2024-12-04 at 4 09 53 PM" src="https://github.com/user-attachments/assets/a3288897-d261-42ba-b38b-cad44184d856">
<img width="1091" alt="Screenshot 2024-12-04 at 4 10 13 PM" src="https://github.com/user-attachments/assets/ac1a35d9-38cc-4a78-9b98-e45b448cf2b8">

2024-12-08 03:47 UTC, sarinali commented on apps/expo/src/app/createpost.tsx
> +                    createPost();
You did not clear the state after posting, is this intentional?

2024-12-10 00:31 UTC, sarinali commented on apps/expo/package.json
> +    "expo": "^52.0.14",
Why did you downgrade the version?

2024-12-11 05:52 UTC, Adventurer-E commented on apps/expo/package.json
> +    "expo": "^52.0.14",
For this I have no idea...

2024-12-12 00:23 UTC, sarinali commented on apps/expo/package.json
> +    "expo": "^52.0.14",
Please don't commit that!

2024-12-20 14:07 UTC, sarinali requested changes

2024-12-20 14:07 UTC, sarinali commented on apps/expo/package.json
> +    "expo-notifications": "~0.29.10",
fix versioning please

2024-12-31 01:51 UTC, sarinali requested changes
Hey! Thanks for the changes, here are a few things I noticed, can you see if it is like that on your version as well?
1. Cancel button and back button on the create post page do not work as intended
2. Cannot dismiss keyboard in the description box (clicking outside does not work, scrolling does not work)
3. Can you change the button colour to shade of `p-40` inside of the `apps/expo/tailwind.config.ts` file? You can see some predefined config colours to pull from there and the one you care about is under `p`.

2025-01-03 03:57 UTC, Adventurer-E commented
> Hey! Thanks for the changes, here are a few things I noticed, can you see if it is like that on your version as well?
> 
> 1. Cancel button and back button on the create post page do not work as intended
> 2. Cannot dismiss keyboard in the description box (clicking outside does not work, scrolling does not work)
> 3. Can you change the button colour to shade of `p-40` inside of the `apps/expo/tailwind.config.ts` file? You can see some predefined config colours to pull from there and the one you care about is under `p`.

For the first and second issue, I tried but cannot reproduce, perhaps because I'm using a simulator.

2025-01-03 04:00 UTC, Adventurer-E commented on apps/expo/src/app/createpost.tsx
>                    createPost();
> Again here you have the method in both, is there a reason for both?

Quite weird. I reduced them to only one occurence and they are working correctly right now.
However, if you check my corrected code now, under createpost.tsx, for FilledButton and OutlinedButton I put onPress on the TouchbleOpacity layer; but under forum.tsx for FloatingButton, I put onPress directly on FloatingButton layer but not on TouchableOpacity. I tried otherwise but the other way around doesn't work, which makes me wonder why 😂

2025-01-04 13:20 UTC, closed without merging